--- #YAML:1.0
name:                Lingua-StopWords
version:             0.09
abstract:            Stop words for several languages.
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.33
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Marvin Humphrey <marvin at rectangular dot com>
